import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class BatteryService {
  batteryData = [
    {
      brand: 'ABARTH',
      models: [
        { year: '2014>', model: 'Abath 500 All', batterySize: '621', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'ALFA ROMEO',
      models: [
        { year: '1978-83', model: 'Alfetta Sedan, Exec, GTtV2000, Giulietta', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1981-83', model: '2.0 GTV Sprint and Export Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1981-83', model: 'Alfetta Automatic', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1981-87', model: '2.5 GTV 6, Alfa 6 and 3, OL and GTV 6', batterySize: '647', alternative: '646', technology: 'SMF' },
        { year: '1982-85', model: 'Alfa GTV 6', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '1983-85', model: 'Alfa 33', batterySize: '639', alternative: '621', technology: 'SMF' },
        { year: '1983-85', model: 'Alfetta 1591, Sprint MK3', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Alfa Spider all Models', batterySize: '668', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'AUDI',
      models: [
        { year: '1981-94', model: 'All Audi Models 100, 200, 500, 500E, 500SE', batterySize: '647', alternative: '661', technology: 'SMF' },
        { year: '1995-99', model: 'All Models A4, A6, A8, Quattro’s, Coupe’s and Cabrio’s', batterySize: '652', alternative: '661', technology: 'SMF' },
        { year: '1997-', model: 'A3 1.8 and 1.8 Turbo, S3', batterySize: '646', alternative: '658', technology: 'SMF' },
        { year: '2000-', model: 'All Models A4, A6, A8, Quattro’s, Coupe’s and Cabrio’s', batterySize: '652', alternative: '652', technology: 'SMF' },
        { year: '2001-', model: 'TT', batterySize: '646', alternative: '658', technology: 'SMF' },
        { year: '2004>', model: 'TT Roadster', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '2004-', model: 'All Models including Diesels', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi A3 all Models', batterySize: '652', alternative: '658', technology: 'SMF' },
        { year: '2007>', model: 'Audi A3 Sportback all Models', batterySize: '652', alternative: '668', technology: 'SMF' },
        { year: '2007>', model: 'Audi A4 all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi A4 Cabrio all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi A6 all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi A8 all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi Q7 all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi RS4 all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi S3 Quattro', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi S6 Quattro Tiptronic', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi S8 Quattro Tiptronic', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi TT Coupé all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi TT Roadster all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Audi R8 FSI all Models', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2009>', model: 'Q7 All', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2010>', model: 'A5 Sports Back', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'A5 Coupe', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'A5 Cabrio', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'R 8', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Q5', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Q3', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'A1 All', batterySize: '652', alternative: '', technology: 'AGM' },
        { year: '2011>', model: 'A8', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2011>', model: 'Q3 All', batterySize: '652', alternative: '668', technology: 'AGM' },
        { year: '2012>', model: 'A3 All', batterySize: '652', alternative: '668', technology: 'AGM' },
        { year: '2012>', model: 'A4 1.8', batterySize: '652', alternative: '668', technology: 'SSM' },
        { year: '2012>', model: 'A4 All Diesel models', batterySize: '668', alternative: '658', technology: 'AGM' },
        { year: '2012>', model: 'Q5 2L Petrol', batterySize: '668', alternative: '658', technology: 'SMF' },
        { year: '2012>', model: 'Q5 All Diesel and 3L Petrol', batterySize: '668', alternative: '658', technology: 'AGM' },
        { year: '2012>', model: 'A5 2L Petrol', batterySize: '652', alternative: '668', technology: 'SSM' },
        { year: '2012>', model: 'A5 Diesel and 3L Petrol', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2013>', model: 'A6 All', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2012>', model: 'A7', batterySize: '658', alternative: '', technology: '' },
      ],
    },
    {
      brand: 'BMW',
      models: [
        { year: '1974-81', model: '525, 528, 530, 535', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '1974-89', model: 'All 5 & 7 Series incl 635, 635 CSI', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '1977-80', model: '3,0L', batterySize: '639', alternative: '621', technology: 'SMF' },
        { year: '1983-91', model: '316, 318 (E30)', batterySize: '628', alternative: '652', technology: 'SMF' },
        { year: '1983-91', model: 'All Models 316i, 318, 320i, 323i, 325i (BU86&87)', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '1988 >', model: '7 Series (E32)', batterySize: '654', alternative: '', technology: 'SMF' },
        { year: '1990 >', model: '5 Series (E34)', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '1990 >', model: '535 only', batterySize: '654', alternative: '', technology: 'SMF' },
        { year: '1991-98', model: '3 Series (E36)', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '1991-98', model: '325TDS (Diesel)', batterySize: '654', alternative: '658', technology: 'SMF' },
        { year: '1991-98', model: '8 Series (E31)', batterySize: '2 x 651', alternative: '', technology: 'SMF' },
        { year: '1997-2002', model: '5, 7, X5, 3 Series E39, E46', batterySize: '652', alternative: '651', technology: 'AGM' },
        { year: '2001-2006', model: '5, 7, X5, 3 Series E39, E46', batterySize: '652', alternative: '651', technology: 'AGM' },
        { year: '2003-2006', model: 'BMW X3 (E83)', batterySize: '675', alternative: '668', technology: 'SMF' },
        { year: '2005-2012', model: '3, 5, 7 & X5 (E60, E70)', batterySize: '675', alternative: '', technology: 'AGM' },
      ],
    },
    {
      brand: 'CHEVROLET / CHRYSLER',
      models: [
        { year: '1979-80', model: 'Rekord & Commodore', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1979-80', model: 'Senator', batterySize: '628', alternative: '622', technology: 'SMF' },
        { year: '1995', model: 'Corvette C4/C5', batterySize: '621', alternative: '646', technology: 'SMF' },
        { year: '2000>', model: 'Lumina', batterySize: '638', alternative: '646', technology: 'SMF' },
        { year: '2002>', model: 'Lumina SS', batterySize: 'Import 75-60', alternative: '', technology: 'SMF' },
        { year: '2002>', model: 'Aveo, Optra', batterySize: '646', alternative: '638', technology: 'SMF' },
        { year: '2002>', model: 'Vivant', batterySize: '646', alternative: '638', technology: 'SMF' },
        { year: '2002>', model: 'Spark', batterySize: '630', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Lumina', batterySize: '622', alternative: '621', technology: 'SMF' },
        { year: '2007-09', model: 'Chevrolet Aveo all Models', batterySize: '615', alternative: '618', technology: 'SMF' },
        { year: '2007-09', model: 'Chevrolet Captiva all Models', batterySize: '639', alternative: '638', technology: 'SMF' },
        { year: '2007-09', model: 'Chevrolet Lumina all Models', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2007-09', model: 'Chevrolet Optra all Models', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2007-09', model: 'Chevrolet Spark all Models', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Chevrolet Ute SS all Models', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Chevrolet Spark', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Chevrolet Aveo', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Chevrolet Cruze', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2010>', model: 'Chevrolet Captiva Petrol/Diesel', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2010>', model: 'Chevrolet Lumina UTE', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2011>', model: 'Chevrolet Sonic 1.3&1.4&1.6', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2011>', model: 'Chevrolet Sonic 1.3&1.4&1.6', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2011>', model: 'Chevrolet Sonic1.4 RS', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012', model: 'Chevrolet Cruise All Models', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2012', model: 'Chevrolet Spark 1.2', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2012>', model: 'Chevrolet Captiva 2.2D', batterySize: '', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Chevrolet Trailblazer 2.8D', batterySize: '658', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'CITROËN / DS',
      models: [
        { year: '1961-81', model: 'All Models ID&DS19, DS20, DS21& Pallas', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1973-80', model: 'All Models GS2200, Special, x 2 & Le Mans', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '2001>', model: 'Xsara, C5 2.0, 3.0', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2001>', model: 'Xsara 1.6 + Picasso 1.6 + 1.8', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2001>', model: 'Xsara & Picasso 1.6, 1.8, 2.0', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2002>', model: 'C2, C3', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2004>', model: 'Berlingo Multispace', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2005>', model: 'C4', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Citroën Berlingo 1,4 and 1.9D panel van', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C1 all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C2 all Models', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C3 all Models', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C3 Pluriel 1,4i', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C3 Pluriel 1,6i Sensodrive*', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C4 all Models', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Citroën C5 2,0 all Models', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2010>', model: 'Citroën C3 Picasso', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Citroën C4', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Citroën C4 Picasso', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Citroën C5', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'DS4 All', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '2012>', model: 'DS3 1.6 THP', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '2012>', model: 'C4', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '2014', model: 'C4Aircross HDI', batterySize: '650S', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'CHERY',
      models: [
        { year: '2010>', model: 'Chery QQ3', batterySize: '630', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Chery J1', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Chery J5', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Chery Tiggo', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '2014>', model: 'Chery J2', batterySize: '646', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'DAIHATSU',
      models: [
        { year: '1997>', model: 'Cuore, Feroza', batterySize: '615', alternative: '630', technology: 'SMF' },
        { year: '1997>', model: 'Rocky', batterySize: '674', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Delta', batterySize: '675', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Gran Move', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '1998>', model: 'Sirion & YRV', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '1998>', model: 'Terios', batterySize: '630', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'YRV, SUV', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Daihatsu Charade all Models', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Daihatsu Copen', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Daihatsu Materia all Models', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Daihatsu Sirion all Models', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Daihatsu Terios all Models', batterySize: '615', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Materia', batterySize: '615', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'FIAT',
      models: [
        { year: '1990>', model: 'Uno All Models', batterySize: '618', alternative: '618', technology: 'SMF' },
        { year: '1999>', model: 'Palio, Siena', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'Uno Mia', batterySize: '618', alternative: '618/9', technology: 'SMF' },
        { year: '2000-06', model: 'Palio, Siena-1.2, 1.6, Weekend, Seicento', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2003-06', model: 'Stilo 1.9 Diesel and Petrol', batterySize: '646', alternative: '612', technology: 'SMF' },
        { year: '2003>', model: 'Multipla, Doblo', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Sceicento', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Panda', batterySize: '612', alternative: '646', technology: 'SMF' },
        { year: '2005>', model: 'Punto', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Palio II all Models', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Panda all Models', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Grande Punto all Models', batterySize: '646', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Bravo all Models', batterySize: '646', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Strada all Models', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Strada X-Space and Adventure', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Uno panel van', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2007>', model: 'Fiat Ducato Vetrato / 10 / 11,5 / 13 all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'All Stilo variants', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Fiat 500', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Croma 2.2 Dynamic all Models', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Doblo Cargo all Models', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Fiat Linea', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2012>', model: 'Punto 1.4 Pop', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Panda All Models', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Quibo', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Fiorino', batterySize: '612', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'FORD',
      models: [
        { year: '1972-83', model: 'Cortina, Granada, 2.0L', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1980-83', model: 'Anglia, Escort, Cortina 1300, 1600', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '1981-86', model: 'FWD Escort, 1300,1400, 1600', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '1983>', model: 'Cortina, Granada with aircon', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '1983>', model: 'Cortina, Granada, 2,0L, Auto', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1983-93', model: 'Sierra, Sapphire All Models', batterySize: '628', alternative: '652', technology: 'SMF' },
        { year: '1986>', model: 'FWD Escort 1400, 1600', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1986>', model: 'FWD Escort, 1300', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '1986-93', model: 'Husky 10 Seater Bus', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1986-93', model: 'Laser, Meteor, Tracer, Some Models', batterySize: '630', alternative: '634', technology: 'SMF' },
        { year: '1990>', model: 'Spectron', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1993>', model: 'Laser, Meteor, Tracer', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1993>', model: 'Sierra, Sapphire All Models w/out Aircon', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '1993>', model: 'Sierra, Sapphire with Aircon', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '1993>', model: 'Telstar & TX 5 All Models', batterySize: '649', alternative: '621', technology: 'SMF' },
        { year: '1996>', model: 'Escort Range', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1996>', model: 'Escort Range with FLAT TERMINALS', batterySize: '627', alternative: '628', technology: 'SMF' },
        { year: '1997>', model: 'Ford Falcon, GLi, Futura, Fairmont, XR6', batterySize: '643', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Ford Fiesta', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '1997>', model: 'Mondeo', batterySize: '628', alternative: '651', technology: 'SMF' },
        { year: '1997>', model: 'Explorer', batterySize: '643', alternative: '639', technology: 'SMF' },
        { year: '1999>', model: 'Meteor, Tracer, Tonic', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2000>', model: 'Focus', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '2000-05', model: 'Ikon', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '2004-05', model: 'Focus ST170', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2004-05', model: 'Focus 1.8TD Diesel', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2004-05', model: 'Mondeo ST 220', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2005-06', model: 'Territory All Models', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Bantam all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford F250 all Models', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Fiesta all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Focus Petrol all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Focus Diesel all Models', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Ikon all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Ford Ka all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Ford Fiesta', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Ford Bantam Diesel', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2010>', model: 'Ford Ikon', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Ford Everest', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Ford Focus 1.6&1.8', batterySize: '651', alternative: '651', technology: 'SMF' },
        { year: '2011>', model: 'Ford Focus Gdi', batterySize: '652', alternative: '651', technology: 'SMF' },
        { year: '2011>', model: 'Ford Figo', batterySize: '619', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Ford Figo diesel', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Ford Kuga 2.5', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Ford Fiesta ecoboost', batterySize: '646', alternative: '628', technology: 'SMF' },
        { year: '2013>', model: 'Ford Kuga 1.6 ecoboost', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Ford Kuga 2.0 Tdci', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2014>', model: 'Ford Ecosport', batterySize: '628', alternative: '646', technology: 'SMF' },
      ],
    },
    {
      brand: 'HONDA',
      models: [
        { year: '1983>', model: 'All models Ballade & Prelude', batterySize: '630', alternative: '', technology: 'SMF' },
        { year: '1996>', model: 'Prelude', batterySize: '638', alternative: '631', technology: 'SMF' },
        { year: '1998>', model: 'Civic 150i, 160i', batterySize: '630', alternative: '631', technology: 'SMF' },
        { year: '1998>', model: 'Prelude VTEC 2.2', batterySize: '634', alternative: '', technology: 'SMF' },
        { year: '1998>', model: 'Odyssey VTEC 2.3', batterySize: '634', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'Civic 170i V-TEC', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'S2000 Roadster', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'CR-V', batterySize: '634 *', alternative: '', technology: 'SMF' },
        { year: '2003>', model: 'Jazz 1.4i, DSi, SUT', batterySize: '616', alternative: '630', technology: 'SMF' },
        { year: '2004>', model: 'Accord', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Honda Accord Executive all Models', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Honda Civic all Models', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Honda CR-V all Models', batterySize: '634 *', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Honda Jazz all Models', batterySize: '616', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Honda S2000', batterySize: '634 *', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Honda Civic Petrol 4door', batterySize: '636 *', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Honda Civic Hatch', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '2012>', model: 'Honda Civic 2.2 D', batterySize: '652', alternative: '652', technology: 'SMF' },
        { year: '2012>', model: 'Honda CRV Petrol all', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '2012>', model: 'Honda Brio 1.2', batterySize: '616', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'HYUNDAI',
      models: [
        { year: '1993>', model: 'Sonata', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1997>', model: 'Accent, Elantra, Tiburon, Elantra CRDi', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1997>', model: 'Sonata', batterySize: '622', alternative: '639', technology: 'SMF' },
        { year: '1999>', model: 'Atoz', batterySize: '616 B', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'Sante Fe', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2003>', model: 'Getz', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2003>', model: 'Sonata', batterySize: '621', alternative: '646', technology: 'SMF' },
        { year: '2003>', model: 'Terracan Diesel 4WD', batterySize: '671', alternative: '652', technology: 'SMF' },
        { year: '2003>', model: 'New Tiburon', batterySize: '621', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Holdown use 628/9, 646', batterySize: '628', alternative: '639', technology: 'SMF' },
        { year: '2005>', model: 'Matrix', batterySize: '646', alternative: '639', technology: 'SMF' },
        { year: '2005>', model: 'Trajet', batterySize: '652', alternative: '630', technology: 'SMF' },
        { year: '2005>', model: 'Tucson', batterySize: '638', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Terracan Petrol', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Accent all Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Atos all Models', batterySize: '616 B', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Bakkie 2,6i dropside', batterySize: '650', alternative: '650', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Elantra all Models', batterySize: '621', alternative: '621', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Getz all Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Santa Fe all Models', batterySize: '621', alternative: '621', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Sonata all Models', batterySize: '639', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Terracan all Models', batterySize: '671', alternative: '671', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Tiburon all Models', batterySize: '621', alternative: '621', technology: 'SMF' },
        { year: '2007>', model: 'Hyundai Azera 3.3 GLS', batterySize: '651', alternative: '651', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai I10', batterySize: '616 B', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai I20', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai I30', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai H1', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai IX35', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Hyundai IX 35 Diesel', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Hyundai I 10', batterySize: '616 B', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Hyundai Elantra 1.6', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Hyundai Elantra 1.8', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Hyundai I 20', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Hyundai I 20 diesel', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Hyundai I 30 1.6', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Hyundai I 30 1.8', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Hyundai Santa-Fe 2.2 D', batterySize: '650S', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Veloster 1.6 GDI', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2009>', model: 'H1 All', batterySize: '650', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'JAGUAR',
      models: [
        { year: '1978>', model: 'XJ6 3.6', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1989>', model: 'S-Type', batterySize: '668', alternative: '654', technology: 'SMF' },
        { year: '2000>', model: 'XJ8, XK Series', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2000>', model: 'Jaguar S-Type all Models', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar XF all Models', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar XJ all Models', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar XJR', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar XK8 Convertible and Coupe', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar XKR Convertible Portfolio/Convertible/Coupe', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2007>', model: 'Jaguar X-Type all Models', batterySize: '658', alternative: '654', technology: 'SMF' },
        { year: '2010>', model: 'Jaguar XKR', batterySize: '658', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'JEEP',
      models: [
        { year: '2007>', model: 'Jeep Cherokee all Models', batterySize: '643', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Jeep Commander all Models', batterySize: '643', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Jeep Compass all Models', batterySize: '643', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Jeep Grand Cherokee all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Jeep Wrangler all Models', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Jeep Patriot all Models', batterySize: '643', alternative: '638', technology: 'SMF' },
        { year: '2012>', model: 'Jeep Wrangler Sahara Unlimited Diesel', batterySize: 'Refer to dealer', alternative: '658', technology: 'SMF' },
        { year: '2011>', model: 'Jeep Wrangler Sahara V6 Petrol', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Jeep Compass 2.4 & 2.4 Petrol', batterySize: 'Refer to dealer', alternative: '612', technology: 'SMF' },
        { year: '2013>', model: 'Jeep Grand Cherokee all Models', batterySize: 'Refer to dealer', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Jeep Cherokee V6 All Sport', batterySize: '643', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'KIA',
      models: [
        { year: '1997>', model: 'Pride', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Sephia', batterySize: '618', alternative: '646', technology: 'SMF' },
        { year: '1997>', model: 'Shuma', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1997>', model: 'Sportage', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Carens', batterySize: '643', alternative: '646', technology: 'SMF' },
        { year: '2000>', model: 'Rio', batterySize: '628', alternative: '621', technology: 'SMF' },
        { year: '2000>', model: 'Spectra', batterySize: '649', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'Carnival Diesel', batterySize: '674', alternative: '', technology: 'SMF' },
        { year: '2001>', model: 'Magentis 2l, 2.5l', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2001>', model: 'Sedona Petrol', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2001>', model: 'Sedona Diesel', batterySize: '650s', alternative: '', technology: 'SMF' },
        { year: '2002>', model: 'Carens CRD', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2002-06>', model: 'Sportage', batterySize: '646', alternative: '649', technology: 'SMF' },
        { year: '2002>', model: 'Carnival (Petrol)', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2002>', model: 'Sorento', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Pregio', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Picanto', batterySize: '616B', alternative: '631', technology: 'SMF' },
        { year: '2007>', model: 'Cerato All', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Kia Cerato all Models', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Kia Picanto all Models', batterySize: '616B', alternative: '630', technology: 'SMF' },
        { year: '2007>', model: 'Kia Rio all Models', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Kia Sorento all Models', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Kia Sportage all Models', batterySize: '643', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Kia Soul', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Kia Proceed', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Kia Sedona', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Picanto', batterySize: '616B', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Rio', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Sportage petrol', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Sportage Diesel', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Sorento Diesel', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Cerato All', batterySize: '646', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Land Rover',
      models: [
        { year: '1992>', model: 'Defender & Discovery', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '1992>', model: 'Range Rover', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '1992-94>', model: 'Defender & Discovery V8 Models', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '1994>', model: 'Range Rover 4.0 & 4.6L', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '1995>', model: 'Defender V8', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1995>', model: 'Defender & Discovery TDi (Local Manu.)', batterySize: '659', alternative: '', technology: 'SMF' },
        { year: '1995>', model: 'Defender TD5', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '1995>', model: 'Defender TDi', batterySize: '650', alternative: '659', technology: 'SMF' },
        { year: '1995>', model: 'Discovery TDi', batterySize: '671', alternative: '637', technology: 'SMF' },
        { year: '1995>', model: 'Discovery V8', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '1998>', model: 'Freelander (Import)', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Discovery TD5 Diesel (Import)', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '1999>', model: 'Discovery V8 Petrol (Import)', batterySize: '671', alternative: '637', technology: 'SMF' },
        { year: '1999>', model: 'Freelander 2.0I TDi (Import)', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '1999>', model: 'Range Rover', batterySize: '671', alternative: '', technology: 'SMF' },
        { year: '1999>', model: 'Freelander 2.0I TDi (Import)', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2005>', model: 'Discovery 3', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Land Rover Defender Petrol', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Land Rover Defender Diesel', batterySize: '674', alternative: '658', technology: 'SMF' },
        { year: '2007>', model: 'Land Rover Discovery all Models', batterySize: '668', alternative: '658', technology: 'SMF' },
        { year: '2007>', model: 'Land Rover Freelander all Models', batterySize: '652', alternative: '668', technology: 'SMF' },
        { year: '2010>', model: 'Land Rover Discovery 4', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Land Rover Range Rover Sport', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Range Rover Evoque SI4&SD4', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Range Rover Sport', batterySize: '658', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Lexus',
      models: [
        { year: '2000>', model: 'IS200', batterySize: '649', alternative: '657', technology: 'AGM' },
        { year: '2000>', model: 'GS300', batterySize: '649', alternative: '', technology: 'AGM' },
        { year: '2000>', model: 'LS430', batterySize: '657', alternative: '', technology: 'AGM' },
        { year: '2000>', model: 'R x 300', batterySize: '652', alternative: '', technology: 'AGM' },
        { year: '2007>', model: 'Lexus GS300 / 300 SE', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Lexus IS250 / SE all Models', batterySize: 'Refer to dealer', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Lexus LS460', batterySize: 'Refer to dealer', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Lexus R x 350 AT and XE AT', batterySize: 'Refer to dealer', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Lexus SC', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Lexus CT 200H', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2012>', model: 'Lexus GS 350', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2012>', model: 'Lexus LX 570', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Lexus RX 350', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2013>', model: 'Lexus IS 350 and Es250', batterySize: '649', alternative: '639', technology: 'SMF' },
      ],
    },
    {
      brand: 'Mahindra',
      models: [
        { year: '2010>', model: 'Mahindra Bolero all Models', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mahindra Scorpio all Models', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mahindra Xylo', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mahindra Tak Tak', batterySize: '622', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mahindra Thar', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Mahindra all 2.2', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Mahindra Quanto', batterySize: '650', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Mahindra XUV 500', batterySize: '650', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Mazda',
      models: [
        { year: '2007>', model: '323 & 626', batterySize: '630', alternative: '631', technology: 'SMF' },
        { year: '2007>', model: '323 All Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1977-84', model: '626 All Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1985>', model: 'Marathon 2.2', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1985-92', model: '626 All Models incl MX6', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '1991>', model: 'Sting, Midge', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1993>', model: 'Etude & Astina', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '1993>', model: 'Soho', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '1995>', model: '626 Imported Model, MX6 & RX8', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '1997>', model: 'Etude', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '1999>', model: 'MX5', batterySize: '636', alternative: '639', technology: 'SMF' },
        { year: '1999>', model: 'Mazda 6, RX8', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '1999>', model: 'Mazda 3', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2003>', model: 'Mazda MX-5 roadster coupé / Soft Top', batterySize: '636', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Mazda RX-8 5-spd and 6 Speed', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Mazda 2 all Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Mazda 3 and Sport all Models', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Mazda 6 all Models', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2007>', model: 'Mazda Cx 7 2.3', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2010>', model: 'Mazda 3', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mazda 6', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2011>', model: 'Mazda 5 2l', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2012>', model: 'Mazda CX 5', batterySize: '649', alternative: '639', technology: 'SMF' },
      ],
    },
    {
      brand: 'Mercedes',
      models: [
        { year: '1988>', model: 'All 8 Cyl Models', batterySize: '654', alternative: '658', technology: 'SMF' },
        { year: '1995>', model: 'C, E & S, CL, CLK, SL, SLK Classes', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2000-06', model: 'A Class', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'ML 270CDI, 320, 430 + Sprinter', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Vito Crew Bus/ Van', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'A Class New Model', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes A all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes B series', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes C / CL and CLK all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes E all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes G55 and GL all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes ML all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes S / SL and SLK all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mercedes GL 320, 500', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mercedes E Class and Coupe', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mercedes CLS and CLC', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mercedes R Class', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Mercedes C Class 180 and 200 non stop start', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'C250 CDI and C350CBI', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'SLK All', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'CLA 180 and 200', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'CLA 220 CDI', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'CLS All', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Mercedes C 63 AMG', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Mercedes B Class All', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Mercedes S Class', batterySize: '1x 668 + 1x 658', alternative: '', technology: 'SMF' },
        { year: '2014>', model: 'Mercedes new A Class ALL', batterySize: '668', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Mitsubishi',
      models: [
        { year: '1974-93', model: 'Colt incl Galant, Tredia 1400, 1600, 1800 & Turbo', batterySize: '630', alternative: '631', technology: 'SMF' },
        { year: '1983>', model: 'L300 & Starwagon', batterySize: '630', alternative: '634', technology: 'SMF' },
        { year: '1985>', model: 'Models Colt &', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1993>', model: 'Pajero', batterySize: '650', alternative: '657', technology: 'SMF' },
        { year: '1999>', model: 'Pajero 2800 intercooled Turbo + Outlander', batterySize: '657', alternative: '650', technology: 'SMF' },
        { year: '1999>', model: 'Pajero 3500 intercooled Turbo', batterySize: '650', alternative: '657', technology: 'SMF' },
        { year: '2000>', model: 'Pajero IO', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2003>', model: 'Lancer all', batterySize: '621', alternative: '649', technology: 'SMF' },
        { year: '2007>', model: 'Mitsubishi Lancer all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mitsubishi Outlander 2,4', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mitsubishi Pajero all Models', batterySize: '650 S', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Mitsubishi Triton all Models', batterySize: '650 S', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Mitsubishi Pajero Sport', batterySize: '650 S', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Mitsubishi ASX 2l', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2011>', model: 'Mitsubishi Pajero 3.2 D', batterySize: '649', alternative: '639', technology: 'SMF' },
      ],
    },
    {
      brand: 'Nissan',
      models: [
        { year: '1972-92', model: 'All Models', batterySize: '610', alternative: '638', technology: 'SMF' },
        { year: '1992>', model: 'Sentra, Sabre, Maxima', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1994>', model: 'SX 1.8, 2.0 ZX 2.8, 3.0', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1997>', model: 'Maxima QX 2.0 & 3.0', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '1998>', model: 'Primera', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2000-05', model: 'Almera', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2000-04', model: 'Primera', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2000-04', model: 'Maxima', batterySize: '649', alternative: '639', technology: 'SMF' },
        { year: '2000>', model: 'Terrano, Patrol Petrol', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '2000>', model: 'Terrano, Patrol Diesel', batterySize: '657', alternative: '', technology: 'SMF' },
        { year: '2003>', model: 'Xtrail Petrol', batterySize: '621', alternative: '639', technology: 'SMF' },
        { year: '2003>', model: 'Xtrail Diesel', batterySize: '657', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Micra', batterySize: '618', alternative: '612', technology: 'SMF' },
        { year: '2004>', model: '350Z', batterySize: '646', alternative: '639', technology: 'SMF' },
        { year: '2005>', model: 'Pathfinder Petrol/Diesel', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan 1400 all Models', batterySize: '610', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan 350Z Coupé* and Roadster', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Hardbody all Models', batterySize: '622', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Micra all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Murano*', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Navara all Models Petrol/Diesel', batterySize: '646', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Pathfinder all Models Petrol/Diesel', batterySize: '646', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Patrol all Models', batterySize: '646', alternative: '638', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Tiida all Models', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan X-Trail all Models', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Livina all Models', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Grand Livina all Models', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Qashqai all Models', batterySize: '639', alternative: '646 Euro Lid', technology: 'SMF' },
        { year: '2007>', model: 'Nissan Primastar 1.9 DCi 100', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Nissan NP 200', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Nissan 370Z', batterySize: '639', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Nissan GTR', batterySize: '636', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Nissan Juke 1.6 Turbo', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2014>', model: 'Nissan Sentra', batterySize: '649', alternative: '', technology: 'SMF' },
        { year: '2014>', model: 'Nissan Juke 1.6 Turbo', batterySize: '649', alternative: '', technology: 'SMF' },
        { year: '2014>', model: 'Nissan Almera', batterySize: '612', alternative: '628', technology: 'SMF' },
      ],
    },
    {
      brand: 'Opel',
      models: [
        { year: '1982-90', model: 'Rekord, Senator All Models', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1984-93', model: 'Ascona, Kadett & Monza All Models', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1993-98', model: 'Astra, Kadett 1.3, 1.4', batterySize: '628', alternative: '646', technology: 'SMF' },
        { year: '1993-98', model: 'Astra, Kadett 1.6, 1.8 & 2.0', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '1999>', model: 'Corsa All Models', batterySize: '618', alternative: '628', technology: 'SMF' },
        { year: '1999>', model: 'Astra CS, CD, 1.6 - 2.0', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2001>', model: 'Omega, Caravan, Coupe', batterySize: '652', alternative: '646', technology: 'SMF' },
        { year: '2002>', model: 'Corsa (Petrol)', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2002>', model: 'Corsa (Diesel)', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2004>', model: 'Meriva & New Astra', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'New Corsa (Petrol)', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'New Corsa (Diesel)', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.4 Essentia*', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.6 Enjoy', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.6 Essentia', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.8 Enjoy', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.9 CDTI Enjoy', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 1.8 Sport', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra 2.0 Turbo Sport', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 1.8', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 1.8 Sport', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 1.9 CDTI', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 1.9 CDTI Sport', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 2.0 Turbo Sport', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 2.0 Turbo*', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra GTC 2.0 Turbo OPC*', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra Twintop 1.8 Enjoy', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Astra Twintop 2.0 Turbo Cosmo*', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Classic 1.4 Essentia', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Classic 1.6 Essentia', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Classic 1.7 CDTI Enjoy', batterySize: '628', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Hatch 1.4 Club', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Hatch 1.4 Sport', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Hatch 1.6 Sport', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Hatch 1.7 CDTI Elegance', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Hatch 1.8 GSi*', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Lite', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Corsa Lite Sport', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Meriva 1.4 Essentia', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Meriva 1.6 Enjoy', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Meriva 1.7 CDTI Enjoy', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Tigra 1.4 Enjoy', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Opel Tigra 1.8 Sport*', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Partner', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Astra Twintop 1.8, 2.0', batterySize: '652', alternative: '651', technology: 'SMF' },
        { year: '2007>', model: 'Astra OPC 2.0, 2.0t', batterySize: '652', alternative: '651', technology: 'SMF' },
        { year: '2007>', model: 'Vivaro 2.0', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Vivaro 1.9 Diesel', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Movano 2.5', batterySize: '651', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Astra All Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Meriva 1.4', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Astra OPC', batterySize: '', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Peugeot',
      models: [
        { year: '1996>', model: '', batterySize: '612', alternative: '628', technology: 'SMF' },
        { year: '1999>', model: '', batterySize: '612', alternative: '618', technology: 'SMF' },
        { year: '2004>', model: '', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2005>', model: '', batterySize: '646', alternative: '628', technology: 'SMF' },
        { year: '2005>', model: 'Peugeot 107 all Models', batterySize: '612', alternative: '646', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 206 all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 207 all Models', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 307 all Models', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 407 all Models', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 607*', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 807 2.2 HDi Pullman', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2007>', model: 'Peugeot 308', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2010>', model: 'Peugeot 3008', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Peugeot 5008', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Peugeot 208 All', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Peugeot 4008', batterySize: '646', alternative: 'Euro Lid', technology: 'SMF' },
        { year: '2011>', model: 'Peugeot 208 HDI', batterySize: '649', alternative: '', technology: 'SMF' },
        { year: '2013>', model: '', batterySize: '651', alternative: 'Euro Lid', technology: 'SMF' },
      ],
    },
    {
      brand: 'Porsche',
      models: [
        { year: '1980>', model: '911 5 & 5.3 LT', batterySize: '628 x 2', alternative: '308 x 2', technology: 'SMF' },
        { year: '1980>', model: '924 & Turbo', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '1980>', model: '928, 928S', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '1980>', model: '944 & Turbo', batterySize: '652', alternative: '646', technology: 'SMF' },
        { year: '1983>', model: 'Boxster', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '1997>', model: '911 Carrera, Turbo, GT2', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Cayenne', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche 911 Carrera / S / 4 / 4S / Cabrio and Tiptronic', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche 911 Carrera 4 Targa / 4 / 4S and Tiptronic', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche 911 Turbo Cabrio', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche 911 Turbo*', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche Boxster / S and Tiptronic', batterySize: '651', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche Cayenne S Tiptronic S / V6 and Turbo', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche Cayman / S and Tripronic', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Porsche GT3 / RS*', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Porsche Panamera', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Porsche Boxster 2.7', batterySize: '652', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Proton',
      models: [
        { year: '2005>', model: 'Proton Gen.2 all Models', batterySize: '628', alternative: '636', technology: 'SMF' },
        { year: '2005>', model: 'Proton Satria Neo 1.6', batterySize: '628', alternative: '636', technology: 'SMF' },
        { year: '2005>', model: 'Proton Savvy all Models', batterySize: '628', alternative: '636', technology: 'SMF' },
        { year: '2010>', model: 'Satria Neo 1.6 GLX', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Proton Persona', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Proton Saga', batterySize: '646', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Range Rover',
      models: [
        { year: '2007>', model: 'Range Rover Sport all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Range Rover TDV8 AT', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Range Rover V8 HSE AT*', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Range Rover Vogue V8SC AT', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'Range Rover Evoque All', batterySize: '668', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Range Rover Sport all Models', batterySize: '658', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Renault',
      models: [
        { year: '1986>', model: 'All Models', batterySize: '630', alternative: '', technology: 'SMF' },
        { year: '1996>', model: 'All Models', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '1996>', model: 'Megane 1.4, 1.6, 1.8, 2.0L, incl Hatch', batterySize: '646', alternative: '634', technology: 'SMF' },
        { year: '1996>', model: 'Coupe 16V', batterySize: '628', alternative: '612', technology: 'SMF' },
        { year: '1996>', model: 'Laguna', batterySize: '652', alternative: '651', technology: 'SMF' },
        { year: '2003>', model: 'Spider', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2003>', model: 'Espace', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2003>', model: 'Scenic 1.6, 2.0L', batterySize: '612', alternative: '625', technology: 'SMF' },
        { year: '2004>', model: 'Clio 1.4, 1.6, 2.0', batterySize: '652', alternative: '618', technology: 'SMF' },
        { year: '2005>', model: 'Vel Satis, Connisseur', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Kangoo Maltix', batterySize: '612', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Modus', batterySize: '646', alternative: '618', technology: 'SMF' },
        { year: '2005>', model: 'Scenic 2', batterySize: '652', alternative: '628', technology: 'SMF' },
        { year: '2003>', model: 'Grand Scenic', batterySize: '643', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Renault Clio 1.2 Va Va Voom 3-dr all Models', batterySize: '612', alternative: '618', technology: 'SMF' },
        { year: '2007>', model: 'Renault Clio 3 all Models', batterySize: '612', alternative: '618', technology: 'SMF' },
        { year: '2007>', model: 'Renault Laguna all Models', batterySize: '646', alternative: '651', technology: 'SMF' },
        { year: '2007>', model: 'Renault Mégane all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Renault Espace 3.5 V6 Privelage AT', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Renault Clio', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Renault Sondero', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Renault Clio New All', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'Renault Duster', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2014>', model: 'Renault Megane new All', batterySize: '652', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Subaru',
      models: [
        { year: '1995>', model: 'Impreza, Legacy, Forester, Outback', batterySize: '634', alternative: '', technology: 'SMF' },
        { year: '1995>', model: 'Some Models', batterySize: '636', alternative: '', technology: 'SMF' },
        { year: '1995>', model: 'Subaru B9 Tribeca AT*', batterySize: '631', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Subaru Tribeca', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Outback Diesel & 3.6R', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2013>', model: 'XV 2.0', batterySize: '615', alternative: '', technology: 'SMF' },
      ],
    },
    {
      brand: 'Suzuki',
      models: [
        { year: '2008>', model: 'Jimny', batterySize: '615', alternative: '630', technology: 'SMF' },
        { year: '2008>', model: 'Swift', batterySize: '615', alternative: '630', technology: 'SMF' },
        { year: '2008>', model: 'SX4', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2008>', model: 'Grand Vitara 2.4, 3.2 V6', batterySize: '638', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'Suzuki Alto', batterySize: '615', alternative: '630', technology: 'SMF' },
      ],
    },
    {
      brand: 'Toyota',
      models: [
        { year: '1980-92', model: 'Cressida', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1987>', model: 'Corolla, Conquest, Sprinter, Avanti, TRD', batterySize: '631', alternative: '630', technology: 'SMF' },
        { year: '1990>', model: 'Previa + Supra', batterySize: '622', alternative: '638', technology: 'SMF' },
        { year: '1996>', model: 'Conquest, Tazz all models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '1997>', model: 'Land Cruiser & Prado Diesel', batterySize: '657', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'Toyota Corolla all Models', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2007>', model: 'Toyota Fortuner all Models', batterySize: '688', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Toyota Etios', batterySize: '615', alternative: '621', technology: 'SMF' },
        { year: '2013>', model: 'Toyota Verso 1.6 & 1.8', batterySize: '646', alternative: '612', technology: 'SMF' },
      ],
    },
    {
      brand: 'Volkswagen',
      models: [
        { year: '1986-93', model: 'Jumbo Golf, Jetta, Fox13 (w/out aircon, all 1600-1800)', batterySize: '628', alternative: '647', technology: 'SSM' },
        { year: '1986-93', model: 'Jumbo Golf 1300, Citi Golf 1300, Fox 1300 & Jetta', batterySize: '618', alternative: '628', technology: 'AGM' },
        { year: '1989>', model: 'Kombi, Microbus, Caravelle', batterySize: '647', alternative: '646', technology: 'SMF' },
        { year: '1997>', model: 'Jumbo Golf, Jetta, Fox (with aircon, all 1600-1800, 2.0L)', batterySize: '647', alternative: '652', technology: 'SMF' },
        { year: '1997>', model: 'Golf 3 & Jetta 3 (All Models incl. VR6)', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Polo Playa & Classic 1.4 & 1.6', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Polo Playa & Classic 1.8', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Golf 4 & Jetta 2.0i Highline', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Golf 4 & Jetta 4 1.9 TDi', batterySize: '652', alternative: '656', technology: 'SMF' },
        { year: '1999>', model: 'Golf 4 & Jetta 4 GTi 1.8 Turbo', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '1999>', model: 'Golf 4 & Jetta 4 1.6, 1.6i & Comfortline', batterySize: '646', alternative: '646', technology: 'SMF' },
        { year: '1999>', model: 'Jetta 2.3 V5', batterySize: '652', alternative: '656', technology: 'SMF' },
        { year: '1999>', model: 'Polo Playa & Classic 1.4 & 1.6', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '1999>', model: 'Polo Playa & Classic 1.8', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2000>', model: 'Passat 1.8 Turbo, 2.8', batterySize: '646', alternative: '652', technology: 'SMF' },
        { year: '2000>', model: 'VW Beetle', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2000>', model: 'Microbus T3, Sharan, T4 / Caravelle', batterySize: '646', alternative: '652', technology: 'SSM' },
        { year: '2000>', model: 'New Polo (Petrol)', batterySize: '646', alternative: '', technology: 'SSM' },
        { year: '2002>', model: 'New Polo (Diesel)', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2002>', model: 'Golf, Jetta & Passat', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2004>', model: 'Touran (All Models)', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2005>', model: 'Golf 5', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2005>', model: 'T5, Caravelle 1.9 TDi', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2005>', model: 'T5, Caravelle 2.5, 3.2 V6', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Caddy Kombi', batterySize: '647', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Caddy Panelvan', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Touareg 4.2 V8', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'Touareg TDi V10', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Beetle all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Caddy all Models', batterySize: '618', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Citi all Models', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW CrossPolo 1.9 TDI', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2007>', model: 'VW Eos all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Golf all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Jetta all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Passat all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Polo all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW T5 all Models', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW T5 Caravelle all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2005>', model: 'VW Touareg all Models', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Vivo', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Vivo Classic', batterySize: '628', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Passat', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Scirocco', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Polo all Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Golf 6', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Jetta 5', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW CC', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Tiguan All Models', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2010>', model: 'VW Touran', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2011>', model: 'VW Jetta 6', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'VW Beetle', batterySize: '646', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'CC Bluemotion Petrol', batterySize: '658', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'CC Bluemotion Diesel', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2012>', model: 'Touareg Bluemotion Petrol', batterySize: '658', alternative: '', technology: 'SSM' },
        { year: '2012>', model: 'Touareg Bluemotion Diesel', batterySize: '658', alternative: '', technology: 'AGM' },
        { year: '2012>', model: 'Passat Bluemotion Petrol', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2012>', model: 'Tiguan Bluemotion Petrol', batterySize: '652', alternative: '', technology: 'SSM' },
        { year: '2012>', model: 'Tiguan Bluemotion Diesel', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Polo 1.2 Diesel Bluemotion', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Golf 7 Stop Start and Bluemotion Petrol', batterySize: '652', alternative: '', technology: 'SMF' },
        { year: '2012>', model: 'Golf 7 Stop Start and Bluemotion Diesel', batterySize: '652', alternative: '', technology: 'SMF' },
      ]
    }
  ];
  getBatteryData() {
    return this.batteryData;
  }
}
